# Setup
title:        Josh's blog ğŸŒ´ â˜€ï¸
tagline:      tech & programming rambles 
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Josh Arnold
  url:        https://linkedin.com/in/josh-arnold-8854a2b0

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
